### ISSUE TITLE
Parser does not work on Dockerfile with custom "extensions"

### ISSUE THREAD

**Issue by hood** [camdencheek/tree-sitter-dockerfile#3]
Example:
Dockerfile.dev won't get its syntax highlighted in latest NeoVim

**Comment by camdencheek** [comment]
Hi @hood!

The highlighter depends on neovim's default filetype detection in order to set the buffer's filetype. According to neovim's `filetype.vim`, only files with the pattern `Dockerfile` and `*.Dockerfile` [will be detected](https://github.com/neovim/neovim/blob/5a24284b8d88098018596fe20ed537c7a98dc9b2/runtime/filetype.vim#L395-L396) as the `dockerfile` file type, and be highlighted with this syntax. 

I'd recommend creating a custom override for your filename by making a file like `~/.config/nvim/ftdetect/dockerfile.vim` with the contents
```vim
au BufRead,BufNewFile Dockerfile.* set filetype=dockerfile
```
